# Generated by Django 3.0.5 on 2021-02-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='urlTable',
            fields=[
                ('url', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('text', models.TextField(default=None)),
                ('deletion_time', models.DateTimeField()),
                ('visited', models.BooleanField(default=False)),
            ],
        ),
    ]
